### ISSUE TITLE
Phone verification

### ISSUE THREAD

**Issue by onixiya1337** [Vedza/NitroSniperGo#217]
Hello,
after using it for about 10 minutes and then logging in via browser it asked me to verify my account using phone number. It has never happened before despite using other bot. Has anyone got this issue? I'm not gonna put my phone number lol

**Comment by DarkGD123** [comment]
This isnt a bug lmao, its just discord is very sensitive when you do something real quick (like enabling invite joiner and lessen the delay to join or getting nitro too fast and etc)

**Comment by inverspe** [comment]
Same happened to my alt account but my alt account still continues to snipe nitro codes so I dont bother adding a phone number

**Comment by iiTrauma** [comment]
> Hello,
> after using it for about 10 minutes and then logging in via browser it asked me to verify my account using phone number. It has never happened before despite using other bot. Has anyone got this issue? I'm not gonna put my phone number lol

is cuz your account tried to claim a invalid code

**Comment by FeelsBadMan1** [comment]
Well that happens if you use a bad accountsetup & bad snipersetup. its recommed to verify them by phone at the account regstration, let them age at least 2 weeks (i do 1 month) and use a delay of 35 - 60 on serverjoins. here my config that i recoming to use to be safe:
![image](https://user-images.githubusercontent.com/40109798/111595516-7de26800-87cc-11eb-81c0-d4f5f0ca9ca8.png)

**Comment by FeelsBadMan1** [comment]
set delay to 5 instead of 25 they say to dm within 10 seconds

**Comment by FeelsBadMan1** [comment]
> Same happened to my alt account but my alt account still continues to snipe nitro codes so I dont bother adding a phone number

yes it still sniping but if it won it wont dm the hoster so he will reroll it.
